"""
Django settings for soddos project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os.path
from pathlib import Path
from decouple import config
import dj_database_url
from django.conf.global_settings import STATICFILES_DIRS, STATIC_ROOT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dy-attre_0v=6ss2g%^!rgyra!oo+-#+)(_!rq06_z@9_evws7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'soddos_one',# Добавляем первое приложени
    'saccount',# Добавляем приложение со входом и регистрацией
    'axes',# Добавляем AXES
    'schat',# Добавляем приложение Чат
    'spost',# Добавляем приложение Посты
]

MIDDLEWARE = [
    'axes.middleware.AxesMiddleware',# добавляем Axes Middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'soddos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')# Указываем путь к папке с шаблонами
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'soddos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL')
    )
}

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


SESSION_COOKIE_SECURE = True  # Использовать только HTTPS для передачи сессий
CSRF_COOKIE_SECURE = True    # Использовать только HTTPS для передачи CSRF-токенов

SECURE_BROWSER_XSS_FILTER = True       # Включает XSS-фильтр браузера
SECURE_CONTENT_TYPE_NOSNIFF = True    # Предотвращает MIME-атаку
X_FRAME_OPTIONS = 'DENY'              # Запрещает загрузку вашего сайта в iframe
SECURE_HSTS_SECONDS = 31536000        # Включает HSTS на год
SECURE_HSTS_INCLUDE_SUBDOMAINS = True # HSTS также для поддоменов


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

#Base folder static in project
STATIC_URL = '/static/'

#way folder static
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Путь для сбора статических файлов (используется для деплоя) /  Path for collecting static files (used for deployment)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


"""
    Бакэнды
"""
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # Axes
    'django.contrib.auth.backends.ModelBackend',  # Django стандартная

]

"""
    Решить проблему с разделением кукисов пользователя и админа. Узнаем только после перекидывания на хостинг
"""
#SESSION_COOKIE_NAME = 'user_sessionid'  # Для сайта пользователей
#CSRF_COOKIE_NAME = 'user_csrftoken'  # Для сайта пользователей
#SESSION_COOKIE_PATH = '/'


"""
    Настройки для django-axes в settings.py
"""
AXES_FAILURE_LIMIT = 5  # Максимальное количество неудачных попыток
AXES_COOLOFF_TIME = 1  # Время блокировки в часах
AXES_LOCK_OUT_AT_FAILURE = True  # Включение блокировки на основе неудачных попыток

"""
    Добавляет в админку функционал Axes. Логи доступа, Ошибки доступа  и Попытки доступа
"""
AXES_ENABLE_ADMIN = True